[[plugins]]
repo = 'Shougo/neocomplete.vim'
lazy = 1
on_event = ['InsertEnter']
hook_source = '''
  execute 'source ' . g:vimdir . '/plugins/neocomplete.vim'
'''

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'mtscout6/syntastic-local-eslint.vim'
