[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
  execute 'source ' . g:vimdir . '/plugins/deoplete.vim'
'''

[[plugins]]
repo = 'neomake/neomake'
on_event = 'BufWritePost'
hook_source = '''
let g:neomake_open_list = 1
augroup MyAutoCmd
  autocmd BufWritePost * Neomake
augroup END
'''
